version: 1
accounts:
- name: alice
  coins:
  - 1000000000samf
- name: bob
  coins:
  - 1000000000samf
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5samf
validators:
- name: alice
  bonded: 100000000samf
