syntax = "proto3";
package junction.evmbridge;

import "amino/amino.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/airchains-network/junction/x/evmbridge/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "junction/x/evmbridge/Params";
  option (gogoproto.equal) = true;

  // bridge_workers defines the list of addresses authorized to unlock tokens
  repeated string bridge_workers = 1;
  // bridge contract address
  string bridge_contract_address = 2;
}